default_config:

automation: !include automations.yaml
script: !include scripts.yaml
stream:
readme:
python_script:
discovery:
frontend: 
  themes: !include_dir_merge_named themes/ 


homeassistant:
  packages: !include_dir_named packages
  external_url: !secret default_url
  internal_url: !secret internal_url
  allowlist_external_dirs:
  - "/tmp"
  - /config/
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation


# logger:
#   default: info
#   logs:
#     homeassistant.components.netatmo: debug
#     homeassistant.components.sensor: debug

recorder:
  purge_keep_days: 15 
  exclude: 
    domains: 
      - camera  
    entities: 
      - camera.henry_map
    event_types: 
      - call_service

zone:
  # This will override the default home zone
  - name: Home
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    radius: 80
    icon: mdi:home

# mqtt:
#   broker: !secret local_ip_nuc
#   username: !secret mosquitto_username
#   password: !secret mosquitto_password
#   discovery: true

  

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistantDB
  username: !secret influxdb_user
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state
  include:
    entities:
      - sensor.gautier_weight
      - sensor.manon_weight
      - sensor.netatmo_maison_salon_pluviometre_rain_today
    entity_globs:
      - sensor.*temperature*
      - sensor.enedis*
      - sensor.elec_*
      - sensor.consommation_*

alarm_control_panel:
  - platform: manual

http:
  use_x_forwarded_for: true
  trusted_proxies: 
    - !secret local_ip_nas
    - !secret ip_public
  cors_allowed_origins:
    - !secret default_url
    - !secret domaine_url
    - https://cast.home-assistant.io

tts:
  - platform: google_cloud
    key_file: google_tts.json
    language: fr-FR
    gender: female
    speed: 0.75
    voice: fr-FR-Wavenet-A
  

proximity:
  home_gautier:
    ignored_zones:
      - travail_gautier
      - travail_manon
    devices:
      - person.gautier
    tolerance: 50
  home_manon:
    ignored_zones:
      - travail_gautier
      - travail_manon
    devices:
      - person.manon
    tolerance: 50

telegram_bot:
  - platform: webhooks
    api_key: !secret telegram_api_key
    parse_mode: html
    allowed_chat_ids:
      - !secret telegram_manon
      - !secret telegram_gautier

notify:
  - name: telegram_gautier
    platform: telegram
    chat_id: !secret telegram_gautier
  - name: telegram_manon
    platform: telegram
    chat_id: !secret telegram_manon
  - platform: discord
    name: discord
    token: !secret discord_bot_token

#media_player:
#  - platform: androidtv
#    name: "Shield-AndroidTV"
#    host: !secret local_ip_shield
#  - platform: androidtv
#    name: "videoprojecteur-AndroidTV"
#    host: !secret local_ip_videoprojecteur

xiaomi_aqara:
  discovery_retry: 10
  gateways:
    - mac: !secret xiaomi_mac_gateway
      key: !secret xiaomi_key_gateway
      host: !secret local_ip_xiaomi_gateway

netatmo:
  client_id: !secret netatmo_client_id
  client_secret: !secret netatmo_client_secret

shelly:
  discovery: true
  sensors:
    - all 
    
smartir:

climate:
  - platform: smartir
    name: Climatisation
    unique_id: climatisation
    device_code: 1940
    controller_data: remote.broadlink_remote
    temperature_sensor: sensor.netatmo_maison_salon_temperature
    humidity_sensor: sensor.netatmo_maison_salon_humidity
    #power_sensor: binary_sensor.ac_power

spotcast:
  sp_dc: !secret spotcast_sp_dc
  sp_key: !secret spotcast_sp_key

weather:
  - platform: darksky
    api_key: !secret dark_sky_api_key

shell_command:
  cec_on: !secret cec_on 
  cec_off: !secret cec_off
  reboot_pi: !secret reboot_pi
  gcode_preview_py: 'python /python_scripts/imgconvert.py {{ states.sensor.klipper_preview_path.attributes["data"] }}'
